### ISSUE TITLE
Resources wiki page outdated?

### ISSUE THREAD

**Issue by Thundermaker300** [Rnen/AdminToolbox#105]
Hi.

I noticed the "Resources" wiki page is ever so slightly outdated. For example, under DamageTypes, the micro and the coke are missing (coke is 25 and the list only goes up to 22, I've been trying to figure out what 23 and 24 are with no luck).

Is this intentional?
Thunder

**Comment by Rnen** [comment]
Yeah thats un-intentional... Not had the time to update the wiki pages in a while :sweat_smile: 
Wiki pages are free for anyone to update, but I've been the only one thus far, hence it taking time

I believe your answer might lie here: https://github.com/Grover-c13/Smod2/blob/master/Smod2/Smod2/API/Player.cs#L14

NONE=0, each list item increments by 1
