### ISSUE TITLE
Lockdown turns off after roundrestart

### ISSUE THREAD

**Issue by ArkhamKn1ght** [Rnen/AdminToolbox#23]
### Is your feature request related to a problem? Please describe.
After roundrestart lockdown doesn't turn off

**Comment by Rnen** [comment]
## KeepSettings & LockDown
The re-introduction of the `KeepSettings` command in the next release will ensure this, since the lockdown will become per-player in the nearest future, instead of globally

[Trello Board](https://trello.com/c/iudt5Zla/3-make-lockdown-work-per-user-instead-of-globally)
[KeepSettings Commit](5a2bc2fbcf0469ae32b8aeb953fd44e69f183785)

**Comment by Rnen** [comment]
Added for next release
